///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AC3CalcTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AC3CalcTestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
    [RepositoryFolder("34b587c8-291c-4a79-82f0-6cd70f0b19b6")]
    public partial class AC3CalcTestsRepository : RepoGenBaseFolder
    {
        static AC3CalcTestsRepository instance = new AC3CalcTestsRepository();
        AC3CalcTestsRepositoryFolders.AdobeFlashPlayer19AppFolder _adobeflashplayer19;
        AC3CalcTestsRepositoryFolders.ExplorerAppFolder _explorer;
        AC3CalcTestsRepositoryFolders.Explorer1AppFolder _explorer1;
        AC3CalcTestsRepositoryFolders.Flashplayer19SaDebugExePropertiesAppFolder _flashplayer19sadebugexeproperties;

        /// <summary>
        /// Gets the singleton class instance representing the AC3CalcTestsRepository element repository.
        /// </summary>
        [RepositoryFolder("34b587c8-291c-4a79-82f0-6cd70f0b19b6")]
        public static AC3CalcTestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AC3CalcTestsRepository() 
            : base("AC3CalcTestsRepository", "/", null, 0, false, "34b587c8-291c-4a79-82f0-6cd70f0b19b6", ".\\RepositoryImages\\AC3CalcTestsRepository34b587c8.rximgres")
        {
            _adobeflashplayer19 = new AC3CalcTestsRepositoryFolders.AdobeFlashPlayer19AppFolder(this);
            _explorer = new AC3CalcTestsRepositoryFolders.ExplorerAppFolder(this);
            _explorer1 = new AC3CalcTestsRepositoryFolders.Explorer1AppFolder(this);
            _flashplayer19sadebugexeproperties = new AC3CalcTestsRepositoryFolders.Flashplayer19SaDebugExePropertiesAppFolder(this);
        }

#region Variables

        string _NewVariable = "";

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("493f1f7a-e882-48db-b2d6-67380a832a22")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("34b587c8-291c-4a79-82f0-6cd70f0b19b6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AdobeFlashPlayer19 folder.
        /// </summary>
        [RepositoryFolder("9a67f28f-bb63-4c68-88d3-82093eea2718")]
        public virtual AC3CalcTestsRepositoryFolders.AdobeFlashPlayer19AppFolder AdobeFlashPlayer19
        {
            get { return _adobeflashplayer19; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("18096a17-2495-4b44-893d-fdd56d87a9c8")]
        public virtual AC3CalcTestsRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Explorer1 folder.
        /// </summary>
        [RepositoryFolder("2a98cd82-b3d4-413a-87a7-cd1396728cec")]
        public virtual AC3CalcTestsRepositoryFolders.Explorer1AppFolder Explorer1
        {
            get { return _explorer1; }
        }

        /// <summary>
        /// The Flashplayer19SaDebugExeProperties folder.
        /// </summary>
        [RepositoryFolder("ca373eac-54d2-4e75-a335-9d5ae2a09853")]
        public virtual AC3CalcTestsRepositoryFolders.Flashplayer19SaDebugExePropertiesAppFolder Flashplayer19SaDebugExeProperties
        {
            get { return _flashplayer19sadebugexeproperties; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
    public partial class AC3CalcTestsRepositoryFolders
    {
        /// <summary>
        /// The AdobeFlashPlayer19AppFolder folder.
        /// </summary>
        [RepositoryFolder("9a67f28f-bb63-4c68-88d3-82093eea2718")]
        public partial class AdobeFlashPlayer19AppFolder : RepoGenBaseFolder
        {
            SelfInfoClass _selfInfo;
            RepoItemInfo _adobeflashplayer19Info;
            RepoItemInfo _maximizeInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new AdobeFlashPlayer19  folder.
            /// </summary>
            public AdobeFlashPlayer19AppFolder(RepoGenBaseFolder parentFolder) :
                    base("AdobeFlashPlayer19", "/form[@title='Adobe Flash Player 19']", parentFolder, 30000, null, true, "9a67f28f-bb63-4c68-88d3-82093eea2718", "")
            {
                _selfInfo = new SelfInfoClass(this);
                _adobeflashplayer19Info = new RepoItemInfo(this, "AdobeFlashPlayer19", "titlebar[@accessiblerole='TitleBar']", 30000, null, "c3bdb003-7a80-414b-bd58-8a96d04fe92a");
                _maximizeInfo = new RepoItemInfo(this, "Maximize", "?/?/button[@accessiblename='Maximize']", 30000, null, "4a32ea10-5ac4-4fc7-ba37-dc80ecd41c23");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "8188070c-1e95-421e-9854-32db59b754c2");
            }

            /// <summary>
            /// The SelfInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9a67f28f-bb63-4c68-88d3-82093eea2718")]
            public class SelfInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SelfInfoClass class constructor.
                /// </summary>
                public SelfInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Self", "", 0, null, "9a67f28f-bb63-4c68-88d3-82093eea2718")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e8c60739-1cd5-41f2-9815-8405c8fe0cef")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e8c60739-1cd5-41f2-9815-8405c8fe0cef");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e8c60739-1cd5-41f2-9815-8405c8fe0cef")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e8c60739-1cd5-41f2-9815-8405c8fe0cef", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("fe3cb269-e4aa-4f6a-a6da-78bbde4055fa")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("fe3cb269-e4aa-4f6a-a6da-78bbde4055fa");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("fe3cb269-e4aa-4f6a-a6da-78bbde4055fa")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("fe3cb269-e4aa-4f6a-a6da-78bbde4055fa", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("5cd4d2a3-1cbb-4c89-a960-85e22d9ca55a")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("5cd4d2a3-1cbb-4c89-a960-85e22d9ca55a");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5cd4d2a3-1cbb-4c89-a960-85e22d9ca55a")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5cd4d2a3-1cbb-4c89-a960-85e22d9ca55a", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <returns>The Screenshot4 image.</returns>
                [RepositoryImage("18a69525-7b50-4aa0-aa00-f64bbc8a6b9c")]
                public CompressedImage GetScreenshot4()
                {
                    return GetImage("18a69525-7b50-4aa0-aa00-f64bbc8a6b9c");
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("18a69525-7b50-4aa0-aa00-f64bbc8a6b9c")]
                public CompressedImage GetScreenshot4(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("18a69525-7b50-4aa0-aa00-f64bbc8a6b9c", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <returns>The Screenshot5 image.</returns>
                [RepositoryImage("ba9161c4-989e-4ed0-9efa-8101399dd836")]
                public CompressedImage GetScreenshot5()
                {
                    return GetImage("ba9161c4-989e-4ed0-9efa-8101399dd836");
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ba9161c4-989e-4ed0-9efa-8101399dd836")]
                public CompressedImage GetScreenshot5(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ba9161c4-989e-4ed0-9efa-8101399dd836", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9a67f28f-bb63-4c68-88d3-82093eea2718")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9a67f28f-bb63-4c68-88d3-82093eea2718")]
            public virtual SelfInfoClass SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AdobeFlashPlayer19 item.
            /// </summary>
            [RepositoryItem("c3bdb003-7a80-414b-bd58-8a96d04fe92a")]
            public virtual Ranorex.TitleBar AdobeFlashPlayer19
            {
                get
                {
                    return _adobeflashplayer19Info.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The AdobeFlashPlayer19 item info.
            /// </summary>
            [RepositoryItemInfo("c3bdb003-7a80-414b-bd58-8a96d04fe92a")]
            public virtual RepoItemInfo AdobeFlashPlayer19Info
            {
                get
                {
                    return _adobeflashplayer19Info;
                }
            }

            /// <summary>
            /// The Maximize item.
            /// </summary>
            [RepositoryItem("4a32ea10-5ac4-4fc7-ba37-dc80ecd41c23")]
            public virtual Ranorex.Button Maximize
            {
                get
                {
                    return _maximizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Maximize item info.
            /// </summary>
            [RepositoryItemInfo("4a32ea10-5ac4-4fc7-ba37-dc80ecd41c23")]
            public virtual RepoItemInfo MaximizeInfo
            {
                get
                {
                    return _maximizeInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("8188070c-1e95-421e-9854-32db59b754c2")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("8188070c-1e95-421e-9854-32db59b754c2")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("18096a17-2495-4b44-893d-fdd56d87a9c8")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _windowsexplorerInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "18096a17-2495-4b44-893d-fdd56d87a9c8", "")
            {
                _windowsexplorerInfo = new RepoItemInfo(this, "WindowsExplorer", "?/?/container[@caption='Running applications']/?/?/toolbar[@accessiblename='Running applications']/button[@accessiblename='Windows Explorer']", 30000, null, "ffcc470c-c8ac-4b38-88d6-feb49ef0a097");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("18096a17-2495-4b44-893d-fdd56d87a9c8")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("18096a17-2495-4b44-893d-fdd56d87a9c8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WindowsExplorer item.
            /// </summary>
            [RepositoryItem("ffcc470c-c8ac-4b38-88d6-feb49ef0a097")]
            public virtual Ranorex.Button WindowsExplorer
            {
                get
                {
                    return _windowsexplorerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The WindowsExplorer item info.
            /// </summary>
            [RepositoryItemInfo("ffcc470c-c8ac-4b38-88d6-feb49ef0a097")]
            public virtual RepoItemInfo WindowsExplorerInfo
            {
                get
                {
                    return _windowsexplorerInfo;
                }
            }
        }

        /// <summary>
        /// The Explorer1AppFolder folder.
        /// </summary>
        [RepositoryFolder("2a98cd82-b3d4-413a-87a7-cd1396728cec")]
        public partial class Explorer1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _flashplayer19sadebugexepropertiesInfo;

            /// <summary>
            /// Creates a new Explorer1  folder.
            /// </summary>
            public Explorer1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer1", "/form[@processname='explorer' and @class='TaskListThumbnailWnd']", parentFolder, 30000, null, true, "2a98cd82-b3d4-413a-87a7-cd1396728cec", "")
            {
                _flashplayer19sadebugexepropertiesInfo = new RepoItemInfo(this, "Flashplayer19SaDebugExeProperties", "?/?/listitem[@accessiblename~'^flashplayer_19_sa_debug\\.e']", 30000, null, "df336508-6f75-45c5-ad4c-395f809180fd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a98cd82-b3d4-413a-87a7-cd1396728cec")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a98cd82-b3d4-413a-87a7-cd1396728cec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Flashplayer19SaDebugExeProperties item.
            /// </summary>
            [RepositoryItem("df336508-6f75-45c5-ad4c-395f809180fd")]
            public virtual Ranorex.ListItem Flashplayer19SaDebugExeProperties
            {
                get
                {
                    return _flashplayer19sadebugexepropertiesInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Flashplayer19SaDebugExeProperties item info.
            /// </summary>
            [RepositoryItemInfo("df336508-6f75-45c5-ad4c-395f809180fd")]
            public virtual RepoItemInfo Flashplayer19SaDebugExePropertiesInfo
            {
                get
                {
                    return _flashplayer19sadebugexepropertiesInfo;
                }
            }
        }

        /// <summary>
        /// The Flashplayer19SaDebugExePropertiesAppFolder folder.
        /// </summary>
        [RepositoryFolder("ca373eac-54d2-4e75-a335-9d5ae2a09853")]
        public partial class Flashplayer19SaDebugExePropertiesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Flashplayer19SaDebugExeProperties  folder.
            /// </summary>
            public Flashplayer19SaDebugExePropertiesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Flashplayer19SaDebugExeProperties", "/form[@title~'^flashplayer_19_sa_debug\\.e']", parentFolder, 30000, null, true, "ca373eac-54d2-4e75-a335-9d5ae2a09853", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "714503d9-e62d-4f2b-bf27-f4809d6b717e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ca373eac-54d2-4e75-a335-9d5ae2a09853")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ca373eac-54d2-4e75-a335-9d5ae2a09853")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("714503d9-e62d-4f2b-bf27-f4809d6b717e")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("714503d9-e62d-4f2b-bf27-f4809d6b717e")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}