///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AC3CalcTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AC3CalcTestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
    [RepositoryFolder("34b587c8-291c-4a79-82f0-6cd70f0b19b6")]
    public partial class AC3CalcTestsRepository : RepoGenBaseFolder
    {
        static AC3CalcTestsRepository instance = new AC3CalcTestsRepository();
        AC3CalcTestsRepositoryFolders.Flex3CalcSwfGoogleChromeAppFolder _flex3calcswfgooglechrome;

        /// <summary>
        /// Gets the singleton class instance representing the AC3CalcTestsRepository element repository.
        /// </summary>
        [RepositoryFolder("34b587c8-291c-4a79-82f0-6cd70f0b19b6")]
        public static AC3CalcTestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AC3CalcTestsRepository() 
            : base("AC3CalcTestsRepository", "/", null, 0, false, "34b587c8-291c-4a79-82f0-6cd70f0b19b6", ".\\RepositoryImages\\AC3CalcTestsRepository34b587c8.rximgres")
        {
            _flex3calcswfgooglechrome = new AC3CalcTestsRepositoryFolders.Flex3CalcSwfGoogleChromeAppFolder(this);
        }

#region Variables

        string _NewVariable = "";

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("493f1f7a-e882-48db-b2d6-67380a832a22")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("34b587c8-291c-4a79-82f0-6cd70f0b19b6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Flex3CalcSwfGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("c0e0f54f-7ba3-4533-9a1f-24888f1ae6d5")]
        public virtual AC3CalcTestsRepositoryFolders.Flex3CalcSwfGoogleChromeAppFolder Flex3CalcSwfGoogleChrome
        {
            get { return _flex3calcswfgooglechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
    public partial class AC3CalcTestsRepositoryFolders
    {
        /// <summary>
        /// The Flex3CalcSwfGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("c0e0f54f-7ba3-4533-9a1f-24888f1ae6d5")]
        public partial class Flex3CalcSwfGoogleChromeAppFolder : RepoGenBaseFolder
        {
            Element633897488InfoClass _element633897488Info;

            /// <summary>
            /// Creates a new Flex3CalcSwfGoogleChrome  folder.
            /// </summary>
            public Flex3CalcSwfGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Flex3CalcSwfGoogleChrome", "/form[@title~'^Flex3Calc\\.swf\\ -\\ Google\\ Ch']", parentFolder, 30000, null, true, "c0e0f54f-7ba3-4533-9a1f-24888f1ae6d5", "")
            {
                _element633897488Info = new Element633897488InfoClass(this);
            }

            /// <summary>
            /// The Element633897488InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("35f883cb-9273-4181-817b-98a761729cb5")]
            public class Element633897488InfoClass : RepoItemInfo
            {
                /// <summary>
                /// Element633897488InfoClass class constructor.
                /// </summary>
                public Element633897488InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Element633897488", "?", 30000, null, "35f883cb-9273-4181-817b-98a761729cb5")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e6128a84-a567-4fd5-af23-17eae2666f94")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e6128a84-a567-4fd5-af23-17eae2666f94");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e6128a84-a567-4fd5-af23-17eae2666f94")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e6128a84-a567-4fd5-af23-17eae2666f94", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0e0f54f-7ba3-4533-9a1f-24888f1ae6d5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0e0f54f-7ba3-4533-9a1f-24888f1ae6d5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element633897488 item.
            /// </summary>
            [RepositoryItem("35f883cb-9273-4181-817b-98a761729cb5")]
            public virtual Ranorex.Unknown Element633897488
            {
                get
                {
                    return _element633897488Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element633897488 item info.
            /// </summary>
            [RepositoryItemInfo("35f883cb-9273-4181-817b-98a761729cb5")]
            public virtual Element633897488InfoClass Element633897488Info
            {
                get
                {
                    return _element633897488Info;
                }
            }
        }

    }
#pragma warning restore 0436
}